### ISSUE TITLE
Placera in en slogan i mainsidan!

### ISSUE THREAD

**Issue by Jangdin** [Jangdin/NewCasual#17]
Slogan eller en text som beskriver Systembolagets affärsidé och koncept.

**Comment by johanlindskog277** [comment]
"For Everything Else, There’s Systembolaget"

**Comment by johanlindskog277** [comment]
Systembolaget – “Be Different”

**Comment by johanlindskog277** [comment]
Systembolaget som är öppet på söndagar.

**Comment by johanlindskog277** [comment]
I need a hug or Systembolaget

**Comment by johanlindskog277** [comment]
Systembolaget - Livet är en fest

**Comment by larsenjulia** [comment]
Färdig
